[env:crowpanel_p4]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = esp32-p4-evboard
framework = arduino
board_build.psram = enabled
board_build.filesystem = littlefs
board_build.partitions = default_16MB.csv
monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/ttyUSB1
monitor_port = /dev/ttyUSB1
board_build.embed_files = c6_slave.bin
build_flags =
    -DBOARD_HAS_PSRAM
    -DBOARD_CROWPANEL_P4
    -DLV_CONF_INCLUDE_SIMPLE
    -I${PROJECT_DIR}
    -I${PROJECT_DIR}/src
    -Wno-deprecated-declarations
build_unflags = -Werror
build_src_flags =
    -Wno-deprecated-enum-enum-conversion
    -Wno-volatile
lib_deps =
    lvgl/lvgl@~8.3.11
    bblanchon/ArduinoJson@^7

[env:crowpanel_s3]
platform = espressif32@6.13.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.psram = enabled
board_upload.flash_size = 4MB
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -DBOARD_HAS_PSRAM
    -DBOARD_CROWPANEL_S3
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLV_CONF_INCLUDE_SIMPLE
    -I${PROJECT_DIR}
lib_deps =
    moononournation/GFX Library for Arduino@1.3.7
    lvgl/lvgl@~8.3.11
